url: http://aifeibao.com

title: AIFEIBAO

keywords: AIFEIBAO

description: AIFEIBAO

address: No.1 Donghu Rd., Daxie Development Zone, Ningbo, China 315812

tel: +86-0574-55875122

fax: +86-0574-26878668

email: aifeibao@aifeibao.com

exclude:
  - README.md
  - style.css
  - style.js
